version: "3"
services:
  web:
    image: docker/getting-started
    restart: unless-stopped
    ports:
      - "80:80"
    links:
      - "fluentd"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: web.access
  fluentd:
    build: ./fluentd/
    volumes:
      - ./fluentd/conf:/fluentd/etc/
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"
  elasticsearch:
    image: elasticsearch:7.13.1
    container_name: elasticsearch
    restart: unless-stopped
    environment:
      - "discovery.type=single.node"
    expose:
      - "9200"
    ports:
      - "9200:9200"
  kibana:
    image: kibana:7.13.1
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"
